//*****************************************************************************
//
// fs.c - File System Processing.
//
//*****************************************************************************
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "driverlib/rom.h"
#include "driverlib/ssi.h"
#include "utils/lwiplib.h"
#include "utils/ustdlib.h"
#include "utils/uartstdio.h"
#include "httpserver/httpd.h"
#include "httpserver/fs.h"
#include "httpserver/fsdata.h"
#include "drivers/io.h"
#include "usbFilesystem/usbFilesystem.h"

//*****************************************************************************
// Include the web file system data for this application.  This file is
// generated by the makefsfile utility, using the following command:
//
//     ./filesystem/makefsfile -i flashFs -o flashFs.h -r -h -q
//
// If any changes are made to the static content of the web pages served by the
// application, this script must be used to regenerate flashFs.h in order
// for those changes to be picked up by the web server.
//*****************************************************************************
#include "filesystem/flashFs.h"

// Function to initialise filesystem
// This will abstract the USB MSC or SD/MMC filesystems
void initFs( void ) {
	initUsbFs();
}

//*****************************************************************************
// Open a file and return a handle to the file, if found.  Otherwise,
// return NULL.  This function also looks for special file names used to
// provide specific status information or to control various subsystems.
// These file names are used by the JavaScript on the "IO Control Demo 1"
// example web page.
//*****************************************************************************
struct fs_file *
fs_open(const char *pcName) {
    const struct fsdata_file *psTree;
    struct fs_file *psFile = NULL;

    // For data file
    FIL *hFile = NULL;
    FRESULT fResult = FR_OK;
    char fnBuffer[128];			// buffer to store /www+filename

    // For log file
    FIL hLogFile;
	FRESULT logResult;
	char logLine[64];
	WORD logLength = 0;
	UINT bytesWritten = 0;
	ULONG historySize = 0;

	// log the requested file to www.log
    logResult = f_open( &hLogFile, "/www.log", FA_OPEN_ALWAYS|FA_WRITE );
    if( logResult != FR_OK ) {
    	UARTprintf( "Logging failed :: %s\n",
    				 StringFromFresult(logResult) );
    }
    else {
    	historySize = (&hLogFile)->fsize;
    	// Seek to end
    	f_lseek(&hLogFile, historySize );
    	usprintf( logLine, "%s\r\n", pcName );
    	logLength = ustrlen( logLine );
    	logResult = f_write( &hLogFile, logLine, logLength, &bytesWritten ) ;
    	if( logResult != FR_OK ) {
    		UARTprintf( "Writing to file failed :: %s\n",
    					 StringFromFresult(logResult) );
    	}
    	else {
    		// @TODO : Do we need a new log?
    	}
    	f_close( &hLogFile );
    }

    // Allocate memory for the file system structure.
    psFile = mem_malloc( sizeof(struct fs_file) );
    if(psFile == NULL) {
        return(NULL);
    }

    // First we will look for any action requests
    // @TODO : implement clean functionality -- like arduino server for actions.
    if( ustrncmp(pcName, "/getDeviceStatus.php", 10) == 0 ) {
    	static char pcBuf[30];

    	io_getDeviceStatus( pcBuf, 30 );

    	psFile->data 		= pcBuf;
    	psFile->len			= strlen( pcBuf );
    	psFile->index		= psFile->len;
    	psFile->pextension	= NULL;
    	return ( psFile );
    }

    // if not any functions, then we will check whether the requested file
    // exists in www folder of USB MSC.
    // @TODO : fix the requested filename with FatFs filename - tricky??
    usprintf( fnBuffer, "/www%s", pcName );			// append '/www'
    // We'll assume filesystem is mounted, otherwise an attempt to open a file
    // will throw an error.
    // allocate memory fot the file handle
    hFile = mem_malloc( sizeof( FIL ) );
    if( hFile == NULL ) {
    	// Huh, we don't have enough memory. Clean up and quit
    	mem_free( psFile );
    	return( NULL );
    }
    // Attempt to open the file on the Fat File System.
    fResult = f_open( hFile, fnBuffer, FA_READ);
    if(fResult == FR_OK)
    {
        psFile->data = NULL;
        psFile->len = 0;
        psFile->index = 0;
        psFile->pextension = hFile;
        return(psFile);
    }
    else {
    	// @TODO : Possible error reporting
    }

    // If I can't find it there, look in the flash fileystem
    // Initialize the psFile system tree pointer to the root of the linked
    // list.
	psTree = FS_ROOT;

	// Begin processing the linked list, looking for the requested file name.
	while(NULL != psTree) {
		// Compare the requested file "pcName" to the file name in the
		// current node.
		if(ustrncmp(pcName, (char *)psTree->name, psTree->len) == 0) {
			// Fill in the data pointer and length values from the
			// linked list node.
			psFile->data = (char *)psTree->data;
			psFile->len = psTree->len;

			// For now, we setup the read index to the end of the file,
			// indicating that all data has been read.
			psFile->index = psTree->len;

			// We are not using any file system extensions in this
			// application, so set the pointer to NULL.
			psFile->pextension = NULL;

			// Exit the loop and return the file system pointer.
			break;
		}

		// If we get here, we did not find the file at this node of the
		// linked list.  Get the next element in the list.
		psTree = psTree->next;
	}

    // If we didn't find the file, psTee will be NULL.  Make sure we
    // return a NULL pointer if this happens.
    if(NULL == psTree) {
        mem_free(psFile);
        psFile = NULL;
    }

    // Return the file system pointer.
    // @TODO : Possible memory leak from hFile and psFile.
    return( psFile );
}

//*****************************************************************************
// Close an opened file designated by the handle.
//*****************************************************************************
void
fs_close(struct fs_file *psFile) {
    // If a Fat file was opened, free its object.
    if( psFile->pextension )
    {
        mem_free( psFile->pextension );
    }
    // Free the main psFile system object.
    mem_free(psFile);
}

//*****************************************************************************
// Read the next chunk of data from the file.  Return the iCount of data
// that was read.  Return 0 if no data is currently available.  Return
// a -1 if at the end of file.
//*****************************************************************************
int
fs_read(struct fs_file *psFile, char *pcBuffer, int iCount) {
    int iAvailable;
    UINT uiBytesRead;
    FRESULT fResult;

	// Check to see if a Fat File was opened and process it.
	if( psFile->pextension ) {
		// Read the data.
		fResult = f_read(psFile->pextension, pcBuffer, iCount, &uiBytesRead);
		if( (fResult != FR_OK) || (uiBytesRead == 0) ) {
			return(-1);
		}
		return((int)uiBytesRead);
	}
    // Check to see if a command (pextension = 1).
	if(psFile->pextension == (void *)1) {
        // Nothing to do for this file type.
        psFile->pextension = NULL;
        return(-1);
    }
    // Check to see if more data is available.
    if(psFile->len == psFile->index) {
        // There is no remaining data.  Return a -1 for EOF indication.
        return(-1);
    }

    // Determine how much data we can copy.  The minimum of the 'iCount'
    // parameter or the available data in the file system buffer.
    iAvailable = psFile->len - psFile->index;
    if(iAvailable > iCount) {
        iAvailable = iCount;
    }

    // Copy the data.
    memcpy(pcBuffer, psFile->data + iAvailable, iAvailable);
    psFile->index += iAvailable;

    // Return the count of data that we copied.
    return(iAvailable);
}

//*****************************************************************************
// Determine the number of bytes left to read from the file.
//*****************************************************************************
int
fs_bytes_left(struct fs_file *psFile) {
	// Check to see if a Fat File was opened and process it.
	if(psFile->pextension) {
		// Return the number of bytes left to be read from the Fat File.
		return(f_size((FIL *)psFile->pextension) -
			   f_tell((FIL *)psFile->pextension));
	}
    // Return the number of bytes left to be read from this file.
	return(psFile->len - psFile->index);
}
